### ISSUE TITLE
Function to request the allowed actions for an API key

### ISSUE THREAD

**Issue by robinkanters** [BitonicNL/bl3p-api#4]
Can we have a function to ask which of the three action types (Read data; Trade; Withdraw) are allowed for a given API key?

Alternatively we could have a dedicated error code for a disallowed action, but I think a separate function would be nicer because an application can request upfront whether it's allowed to perform certain actions.

**Comment by gnaoot** [comment]
Thanks for the feature request. This could indeed be a useful call for some uses, we'll add it to our  issues list.
