### ISSUE TITLE
Withdrawal account_id

### ISSUE THREAD

**Issue by robinkanters** [BitonicNL/bl3p-api#6]
The docs for a new withdrawal specify:

> `account_id` string
> 
> IBAN account-id (that is available within the regarding BL3P account)

However, I cannot find this in any of the request responses. Where do I retrieve the `account_id`?

**Comment by gnaoot** [comment]
Account_id stands for your bank account number. There is currently no call to retrieve your bank account numbers but they are (usually) quite static so we don't believe that's a necessary call to implement.

**Comment by robinkanters** [comment]
Ah okay, the docs suggested to me that this is some db id that I need to provide, it wasn't clear that it's a bank account number. Thanks!
