### ISSUE TITLE
Timestamp format inconsistency

### ISSUE THREAD

**Issue by robinkanters** [BitonicNL/bl3p-api#7]
So when doing different types of requests, I've noticed that sometimes the dates are in milliseconds (such as for the [last 1000 trades request](https://github.com/BitonicNL/bl3p-api/blob/master/docs/public_api/http.md#23---last-1000-trades)), and sometimes the timestamps are in seconds (such as for the [transaction history request](https://github.com/BitonicNL/bl3p-api/blob/master/docs/authenticated_api/http.md#31---get-your-transaction-history)).

Is that intended and should I compensate for that, or is that a bug?

![image](https://cloud.githubusercontent.com/assets/1043866/22626571/a05c0916-ebb0-11e6-861c-bcdb829781b0.png)
![image](https://cloud.githubusercontent.com/assets/1043866/22626573/abf57488-ebb0-11e6-9ef8-750c03c6bc90.png)

**Comment by robinkanters** [comment]
@gnaoot do you have thoughts on this? can anybody offer some insight?

**Comment by gnaoot** [comment]
Sorry for the late reply.
I have no explanation for this inconsistency other than it could be regarded as a design flaw. We will fix this in a future API version (v2).

**Comment by robinkanters** [comment]
Then can we add this to the documentation? It took me quite a white to debug

**Comment by gnaoot** [comment]
Will do!
