### ISSUE TITLE
Unable to use the GO api implementation

### ISSUE THREAD

**Issue by VictorHartman** [BitonicNL/bl3p-api#8]
I was trying out the API using the go implementation. However when running the example code I get the error: "Illegal base64 data at input byte 4". 

There's probably going something wrong when creating an API instance. When making my own API instance, I get the following error: "Illegal base64 data at input byte 84".

I made this issue since there isn't much documentation and the error isn't that helpful.

**Comment by rvzanten** [comment]
It was the idea that you defined your keys in the bl3p.go package.
I have just updated the code so you can do this in your package more easily.
See: https://github.com/BitonicNL/bl3p-api/commit/738f0d0cf8b5ce0042400ffab49c72519f853cb7
That will fix the issue.
